### ISSUE TITLE
How to configurate nextAuth to login into panel

### ISSUE THREAD

**Issue by grzegorzCieslik95** [Kiranism/next-shadcn-dashboard-starter#1]
Hi,
Many thanks for this code, it helps me to create my panel faster. I have problem with configuration of nextAuth. When i try use dumy email i have error like "There is a problem with the server configuration."

How can i fix this?

**Comment by Kiranism** [comment]
Glad that helped you! Try replacing env.text with env.local and double-check the NextAuth secret. Let me know if that helps!

**Comment by grzegorzCieslik95** [comment]
I generated secret from this page https://generate-secret.vercel.app/32 and i changed file name from env.text to env.local but still have this error

`JWEDecryptionFailed: decryption operation failed, 'decryption operation failed`

**Comment by Kiranism** [comment]
You're welcome!
