### ISSUE TITLE
I dont know what is happening 

### ISSUE THREAD

**Issue by Manoj-kumar-C** [Kiranism/next-shadcn-dashboard-starter#12]
![image](https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/90634510/9b0a4d55-7af7-4ba4-bb47-bd2dcd32b9e4)

Can anyone explain plz

**Comment by Manoj-kumar-C** [comment]
My Github Repo: https://github.com/Manoj-kumar-C/next-shadcn-dashboard

**Comment by Manoj-kumar-C** [comment]
UPLOADTHING_SECRET=
UPLOADTHING_APP_ID=



NEXTAUTH_URL = http://localhost:3000
NEXTAUTH_SECRET=


can you explain what will be the values do I need to give

**Comment by Kiranism** [comment]
@Manoj-kumar-C  Follow this! Add the values and copy paste whole file into vercel env input.

# Add Uploadthing secret and appId to setup fileupload https://uploadthing.com/

UPLOADTHING_SECRET=
UPLOADTHING_APP_ID=

# Next auth https://next-auth.js.org/configuration/options
# Run this command to generate a a new NEXTAUTH_SECRET
# $ openssl rand -base64 32

NEXTAUTH_URL = http://localhost:3000
NEXTAUTH_SECRET=

# Go to github and setup the oauth configuration
# https://next-auth.js.org/providers/github#configuration
# https://github.com/settings/developers

GITHUB_ID = 
GITHUB_SECRET =

**Comment by Manoj-kumar-C** [comment]
NEXTAUTH_URL = http://localhost:3000


What will be the NEXTAUTH_URL Value -- I have set the remaining values

**Comment by Kiranism** [comment]
> NEXTAUTH_URL = http://localhost:3000
> 
> What will be the NEXTAUTH_URL Value -- I have set the remaining values.

deployed url.

**Comment by Manoj-kumar-C** [comment]
ok 👍👍. Done SuccesfullY . Thank You

**Comment by Manoj-kumar-C** [comment]
![image](https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/90634510/0718be48-3bdc-4d02-bf34-f74cd0e09072)
🔥🔥

**Comment by Kiranism** [comment]
@Manoj-kumar-C Good Job 🥂
