### ISSUE TITLE
How to delete row from databale

### ISSUE THREAD

**Issue by binfask** [Kiranism/next-shadcn-dashboard-starter#14]
in my case i deleted data from data base by calling API from onConfirm() but the data is not removing from data table

**Comment by m0nx73r** [comment]
Hey @binfask, please share your code too
[Check this](https://stackoverflow.com/help/how-to-ask)

**Comment by binfask** [comment]
the code from my cellAction component :
`"use client";
import { AlertModal } from "@/components/modal/alert-modal";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Car } from "@/constants/data";
import { deleteCar } from "@/lib/actions/car.actions";
import { Edit, MoreHorizontal, Trash } from "lucide-react";
import { useRouter } from 'next/navigation';
import { useState } from "react";
import { useToast } from "../../ui/use-toast";
import { refreshcarpage } from "./refresh";

interface CellActionProps {
  data: Car;
}

export const CellAction: React.FC<CellActionProps> = ({ data }) => {
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const router = useRouter();
  const { toast } = useToast();

  const handleNavigate = async () => {
    // Optional: Perform any actions before navigation
    await router.push('/admin/car');
  };

  const onConfirm = async () => {
    setLoading(true);
    try {
      await deleteCar(data._id);
      toast({
        title: "Success",
        description: "Car deleted successfully",
      });
      setOpen(false);
      
      router.prefetch(`/admin/car`);
    } catch (error) {
      console.error("Error deleting car:", error);
      toast({
        title: "Error",
        description: "Error deleting car",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      <AlertModal
        isOpen={open}
        onClose={() => setOpen(false)}
        onConfirm={onConfirm}
        loading={loading}
      />
      <DropdownMenu modal={false}>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" className="h-8 w-8 p-0">
            <span className="sr-only">Open menu</span>
            <MoreHorizontal className="h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuLabel>Actions</DropdownMenuLabel>

          <DropdownMenuItem
            onClick={() => router.push(`/admin/car/${data._id}`)}
          >
            <Edit className="mr-2 h-4 w-4" /> Update
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => setOpen(true)}>
            <Trash className="mr-2 h-4 w-4" /> Delete
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </>
  );
};
`

**Comment by Kiranism** [comment]
You need to revalidate the data or refetch it to obtain the latest updated data.

**Comment by Kiranism** [comment]
> You need to revalidate the data or refetch it to obtain the latest updated data.

[revalidatePath](https://nextjs.org/docs/app/api-reference/functions/revalidatePath) or [router.refresh](https://nextjs.org/docs/app/api-reference/functions/use-router) also works
