### ISSUE TITLE
"redirect_uri_mismatch" Error from Github OAuth

### ISSUE THREAD

**Issue by hitesh-c** [Kiranism/next-shadcn-dashboard-starter#2]
Hi, I tried deploying this repository, But I am facing a error with Next Auth. My application is redirecting to this after successful Login with Github. Please help me

```https://next-dashboard-pi-nine.vercel.app/?callbackUrl=https://next-dashboard-pi-nine.vercel.app/dashboard?error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=DgW_BIG6i0ULFBuA0xEl2ArAVOAFKNbkCesB-RRLyYo&error=redirect_uri_mismatch```

**Comment by Kiranism** [comment]
Did you setup github config for oauth? 
https://github.com/settings/developers

**Comment by hitesh-c** [comment]
Thanks for replying,

Yes, I did. NextAuth is redirecting back to same sign in page with query params code and state. I am not able to find out why it is not redirecting to dashboard like your deployed version. I have just started learning next.JS

**Comment by Kiranism** [comment]
Make sure to mention your callback URL in the GitHub OAuth settings. Check if you have configured it correctly with your hosted app, like this in the Authorization callback URL:

https://domain/api/auth/callback/github

**Comment by hitesh-c** [comment]
Thanks, It is solved.
