### ISSUE TITLE
Sidebar is not displaying properly in Kanban

### ISSUE THREAD

**Issue by aymericderazey** [Kiranism/next-shadcn-dashboard-starter#21]
Sidebar is not displaying properly in Kanban when adding multiple sections
<img width="1262" alt="SCR-20240531-kfoa" src="https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/135407768/0c3809b3-1a49-4639-895e-5aaf4898a97d">

**Comment by Kiranism** [comment]
Thanks for reporting the issue. I've fixed the problem.
