### ISSUE TITLE
Scroll does not work on small devices

### ISSUE THREAD

**Issue by matiasleal98** [Kiranism/next-shadcn-dashboard-starter#3]
First of all I want to thank the creator of this repository for his great work. 

I have noticed that by decreasing the size of the browser window the scroll stops working. The bar does not appear, nor is it possible to scroll with the mouse. I have tried from Mac Pro and an iPhone 12 and I have had the same problem. This can be seen on the [profile page](https://next-shadcn-dashboard-starter.vercel.app/dashboard/profile).

Same issue in [create product page](https://next-shadcn-dashboard-starter.vercel.app/dashboard/user/new)

**Comment by Kiranism** [comment]
Hey, thanks for reporting. Yeah, I fixed that issue. Please take a pull, and let me know if there are any more issues.
