### ISSUE TITLE
How to deploy your project on Netlify?

### ISSUE THREAD

**Issue by SWS-5007** [Kiranism/next-shadcn-dashboard-starter#34]
Hello, 
How are you?
I just cloned your repo.
And I am going to deploy that on Netlify.
And then, I am getting this error:
![image](https://github.com/user-attachments/assets/0ff98bb3-b42c-4be6-a222-cb4a2aaca9e0)

Of course, I followed all steps as your readme.
And also, I run your project in my local successfully.
When I deploy your project on Netlify, I set all Necessary Environment Variables including `GITHUB_ID`, `GITHUB_SECRET`, `NEXTAUTH_SECRET`, `NEXTAUTH_URL`.
![image](https://github.com/user-attachments/assets/ee43dace-1e6c-47d0-9706-fe804ed3fe65)

![image](https://github.com/user-attachments/assets/67782325-138a-4f80-b400-6167e9ce18a5)

![image](https://github.com/user-attachments/assets/da67bfd2-233c-419e-8363-2fdbfd185d39)

What is wrong yet?
How to solve this problem?

Please help me kindly.
Best regards.

**Comment by SWS-5007** [comment]
One more.
As you can see here, I can see login page.
![image](https://github.com/user-attachments/assets/56c6610b-7ead-40f2-b9b8-e42ed7c519ca)

But When I click the "Continue With Email" Button, I am getting current error.

Best

**Comment by Kiranism** [comment]
> Hello, How are you? I just cloned your repo. And I am going to deploy that on Netlify. And then, I am getting this error: ![image](https://private-user-images.githubusercontent.com/119567356/355918695-0ff98bb3-b42c-4be6-a222-cb4a2aaca9e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTU2NDYsIm5iZiI6MTcyMzA1NTM0NiwicGF0aCI6Ii8xMTk1NjczNTYvMzU1OTE4Njk1LTBmZjk4YmIzLWI0MmMtNGJlNi1hMjIyLWNiNGEyYWFjYTllMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxODI5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzg0ZTg2NmU4ZTE5OTJkNzA1MjU1YzNjNzEwMDMzOThiNjQzZmI3ZjZmMWM2ODdlMDA0MTA4YWRlZmY4OTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mB7UxmXkmX5x1gfTLPIYGuWYitWe4gjEMxztDOqpX_U)
> 


Hey, can you share the server logs from netlify while logging in?

**Comment by SWS-5007** [comment]
> > Hello, How are you? I just cloned your repo. And I am going to deploy that on Netlify. And then, I am getting this error: ![image](https://private-user-images.githubusercontent.com/119567356/355918695-0ff98bb3-b42c-4be6-a222-cb4a2aaca9e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNTU2NDYsIm5iZiI6MTcyMzA1NTM0NiwicGF0aCI6Ii8xMTk1NjczNTYvMzU1OTE4Njk1LTBmZjk4YmIzLWI0MmMtNGJlNi1hMjIyLWNiNGEyYWFjYTllMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QxODI5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Nzg0ZTg2NmU4ZTE5OTJkNzA1MjU1YzNjNzEwMDMzOThiNjQzZmI3ZjZmMWM2ODdlMDA0MTA4YWRlZmY4OTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mB7UxmXkmX5x1gfTLPIYGuWYitWe4gjEMxztDOqpX_U)
> 
> Hey, can you share the server logs from netlify while logging in?

Here it is:

```
Aug 8, 03:32:42 AM: 8eb0da64 ERROR  [auth][error] UntrustedHost: Host must be trusted. URL was: https://phrasly-fork.netlify.app/api/auth/error. Read more at https://errors.authjs.dev#untrustedhostAug 8, 03:32:42 AM: 8eb0da64 ERROR      at /var/task/.next/server/chunks/925.js:393:46983
    at iq (/var/task/.next/server/chunks/925.js:393:49661)
    at async /var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:34666
    at async eS.execute (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:25813)
    at async eS.handle (/var/task/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:35920)
    at async doRender (/var/task/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/var/task/node_modules/next/dist/server/base-server.js:1599:28)
```

**Comment by SWS-5007** [comment]
Oh, Yea!
I just found the solution.
I solved the error by adding New Environment Variable on Netlify.
`AUTH_TRUST_HOST="https://phrasly-fork.netlify.app" `
And After Redeployed, everything works well.
Thanks.
