### ISSUE TITLE
Request Sub Menu

### ISSUE THREAD

**Issue by beysach** [Kiranism/next-shadcn-dashboard-starter#41]
I kindly request the addition of a sub-menu feature for the slider navbar. Thank you!

**Comment by Kiranism** [comment]
Hey, do you have any reference or image of it?

**Comment by beysach** [comment]
![image](https://github.com/user-attachments/assets/0ee8550d-9a0c-43fb-903e-25b556627f6c)
here is the reference

**Comment by Kiranism** [comment]
Hey @beysach  I added the sub-menu—have you checked it out yet? Shadcn will officially release the sidebar component soon. Once it's out, maybe we can utilize that. :)

**Comment by beysach** [comment]
Thank you! It's looking really good. If you could add an expand item animation like Accordion, I think it would enhance it even better.
