### ISSUE TITLE
Sidebar is hidden after components update

### ISSUE THREAD

**Issue by xumix** [Kiranism/next-shadcn-dashboard-starter#46]
So I've updated all the components to the latest versions and now the sidebar is hidden at login screen because `lg-flex` class is not overriding the `hidden`
Same happened to aside and the profile picture in the dashboard

**Comment by xumix** [comment]
Looks like new Uploadthing css styles mess up the tailwind styles

**Comment by Kiranism** [comment]
hey @xumix drop a screenshot for better understanding :)

**Comment by Kiranism** [comment]
> Looks like new Uploadthing css styles mess up the tailwind styles, I've removed the `import '@uploadthing/react/styles.css';` line and everything works now

Thanks for this! I completely got rid of UploadThing, and this was missing from my sight.
