### ISSUE TITLE
Consider fluid to reduce tailwind complexity

### ISSUE THREAD

**Issue by downright-development** [Kiranism/next-shadcn-dashboard-starter#52]
Love the starter! I use it a ton - you should consider adding "fluid" https://fluid.tw to help reduce the necessary tailwind across the starter :)

**Comment by Kiranism** [comment]
Pretty good, but I wonder how many folks would actually be comfortable with it.

**Comment by downright-development** [comment]
Good point - it's definitely a pretty opinionated way (though so nice). That said it's pretty new, hopefully it'll catch on!
