### ISSUE TITLE
table is not responsive 

### ISSUE THREAD

**Issue by rahilansari261** [Kiranism/next-shadcn-dashboard-starter#53]

**Comment by rahilansari261** [comment]
overflow-x-auto wiil do the work in main tag

**Comment by Doraneko1996** [comment]
> overflow-x-auto wiil do the work in main tag

I can't get it to work. Could you please give me an example?

**Comment by Kiranism** [comment]
> > overflow-x-auto wiil do the work in main tag
> 
> I can't get it to work. Could you please give me an example?

Hey, try this [sol](https://github.com/Kiranism/next-shadcn-dashboard-starter/issues/56#issuecomment-2461298423)
