### ISSUE TITLE
chore: switch package manager from npm to pnpm

### ISSUE THREAD

**Issue by Kiranism** [Kiranism/next-shadcn-dashboard-starter#65]

**Comment by mosabalrsaheed** [comment]
HI @Kiranism.

Delete the file 'package-lock.json'. then use the command [pnpm](https://pnpm.io/installation) install normally.

If you face any issues just mention it back here and will be able to support you.

**Comment by Kiranism** [comment]
Yup. I just added the issue as a checklist.
