### ISSUE TITLE
In localhost getting issue after signup

### ISSUE THREAD

**Issue by gowthm** [Kiranism/next-shadcn-dashboard-starter#7]
Can you please explain why i am getting after signup or when redirect dashboard router.

<img width="1065" alt="image" src="https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/50840420/021aaedd-f4d0-4397-b98a-9dc96ea6f97c">

**Comment by Kiranism** [comment]
Hey, can you check and send the error logs in the code editor console?

**Comment by gowthm** [comment]
https://next-auth.js.org/warnings#nextauth_url
[next-auth][warn][NO_SECRET]
https://next-auth.js.org/warnings#no_secret
[next-auth][error][NO_SECRET]
https://next-auth.js.org/errors#no_secret


only getting like this

**Comment by bdhamithkumara** [comment]
first, create .env file like env.example.txt

![image](https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/67802429/7d3a53ae-ed71-416a-8411-1a7579401046)

after that run this code in your terminal 

`openssl rand -base64 32`

it will generate code like this

![image](https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/67802429/83006743-9a8c-4c76-9cec-355d0e3be191)

after that copy and paste that as your NEXTAUTH_SECRET.

**Comment by Kiranism** [comment]
@bdhamithkumara appreciate your help!

**Comment by nfvelten** [comment]
I think it would be nice to add some info about this to the README. It'll help avoid confusion
