### ISSUE TITLE
The page is unresponsive after opening the confirmation modal

### ISSUE THREAD

**Issue by AmulyaShrestha** [Kiranism/next-shadcn-dashboard-starter#9]
#### Additional details
- The issue is replicating only for delete confirmation modals.

#### Replication

https://github.com/Kiranism/next-shadcn-dashboard-starter/assets/39824625/f271ad2a-b466-451d-94dd-27deab4141f5

**Comment by Kiranism** [comment]
@AmulyaShrestha Hey, thanks for pointing that out. I've fixed the problem

**Comment by AmulyaShrestha** [comment]
@Kiranism Thanks for the update!
